# filepath: /Users/vspaswin/develop/spring-ai-demo/docker-compose.yml
services:
  user-management-api:
    container_name: user-management-api
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-management-db:5432/your_db_name
      SPRING_DATASOURCE_USERNAME: your_db_user
      SPRING_DATASOURCE_PASSWORD: your_db_password
    depends_on:
      user-management-db:
        condition: service_healthy
    networks:
      - user-management-network

  user-management-db:
    container_name: user-management-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user -d your_db_name"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user-management-data:/var/lib/postgresql/data
    networks:
      - user-management-network

volumes:
  user-management-data:

networks:
  user-management-network:
    driver: bridge