services:
  user-management-sonarqube:
    container_name: user-management-sonarqube
    image: sonarqube:10.3.0-community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://user-management-sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - user-management-sonar-data:/opt/sonarqube/data
      - user-management-sonar-extensions:/opt/sonarqube/extensions
      - user-management-sonar-logs:/opt/sonarqube/logs
    depends_on:
      - user-management-sonar-db

  user-management-sonar-db:
    container_name: user-management-sonar-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - user-management-sonar-db-data:/var/lib/postgresql/data

volumes:
  user-management-sonar-data:
  user-management-sonar-extensions:
  user-management-sonar-logs:
  user-management-sonar-db-data: 