pipeline:
  identifier: Build_spring_ai_demo_1739805933960
  name: Build spring-ai-demo
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: build
        identifier: GitClone
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: GitHubKarate
                    repoName: spring-ai-demo
                    build:
                      type: branch
                      spec:
                        branch: feature/harness
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
