pipeline:
  identifier: Build_spring_ai_demo_1739805933960
  name: Build spring-ai-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: GitHubKarate
        repoName: spring-ai-demo
  stages:
    - stage:
        identifier: build
        name: build
        type: CI
        failureStrategies:
          - onFailure:
              action:
                type: MarkAsFailure
              errors:
                - Unknown
        spec:
          org: default
          caching:
            enabled: true
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: docker_compose
                  type: Run
                  name: Docker Compose Up
                  spec:
                    connectorRef: <+input>
                    command: |
                      docker-compose up --build -d
                    type: Run
                  timeout: ""
              - step:
                  identifier: runTests
                  type: Test
                  name: Run Tests
                  spec:
                    connectorRef: <+input>
                    command: mvn test
                    testReportPaths:
                      - target/surefire-reports/**/*
                    type: Run
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
